name: CI

on: [push, pull_request]

jobs:
  windows-cmake:
    name: Windows cmake ${{matrix.Configuration}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug]
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        cmake --preset='Ninja-${{matrix.Configuration}}'
        cmake --build build/Ninja-${{matrix.Configuration}}

    - name: Run test
      run: |
        pwd
        ./build/Ninja-${{matrix.Configuration}}/${{matrix.Configuration}}/dxvk-test.exe

  linux-cmake:
    name: Linux cmake ${{matrix.Configuration}}
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive

    - name: Install libs
      run: |
        sudo apt-get update && sudo apt-get install mesa-vulkan-drivers vulkan-tools libvulkan-dev glslang-tools ninja-build libjson-perl spirv-headers wine64-tools
    - name: Build
      run: |
        export CC=gcc && export CXX=g++
        ${CXX} --version && cmake --version
        cmake --preset=Ninja-${{matrix.Configuration}}
        cmake --build build/Ninja-${{matrix.Configuration}}

    - name: Run test
      run: |
        ldd ./build/Ninja-${{matrix.Configuration}}/Debug/dxvk-test
        echo ${{matrix.Configuration}} test result:
        ./build/Ninja-${{matrix.Configuration}}/${{matrix.Configuration}}/dxvk-test
